# Make sure to check the documentation at http://goreleaser.com
builds:
  - ldflags:
      - -w -s -X "github.com/kairos-io/provider-kairos/internal/cli.VERSION={{.Env.VERSION}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    main: ./
    id: "kairos-cli"
    binary: "kairos-cli"
  - ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    main: ./cli/kairosctl
    id: "kairosctl"
    binary: "kairosctl"
source:
  rlcp: true
  enabled: true
  name_template: 'kairos-cli-{{ .Tag }}-source'
archives:
  # Default template uses underscores instead of -
  - name_template: >-
      kairos-cli-
      {{ .Tag }}-
      {{ .Os }}-
      {{ .Arch }}
      {{ if .Arm }}v{{ .Arm }}{{ end }}
    id: kairos-id
    builds:
      - "kairos-id"
  - name_template: >-
      kairos-register-
      {{ .Tag }}-
      {{ .Os }}-
      {{ .Arch }}
      {{ if .Arm }}v{{ .Arm }}{{ end }}
    id: kairosctl
    builds:
      - "kairosctl"
checksum:
  name_template: 'kairos-cli-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
